# Generated by Django 5.2.5 on 2025-08-14 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название коммутатора')),
                ('ip_address', models.GenericIPAddressField(protocol='IPv4', verbose_name='IP-адрес')),
                ('ports_count', models.PositiveIntegerField(verbose_name='Количество портов')),
            ],
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Номер порта')),
                ('connected_device', models.CharField(blank=True, max_length=200, null=True, verbose_name='Подключенное устройство')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4', verbose_name='IP-адрес устройства')),
                ('device_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название устройства')),
                ('status', models.CharField(choices=[('up', 'Включен'), ('down', 'Выключен')], max_length=50, verbose_name='Состояние')),
                ('switch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='switchinfo.switch')),
            ],
        ),
    ]
