# Generated by Django 5.2.5 on 2025-08-15 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switchinfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='port',
            name='addInfo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Дополнительная информация'),
        ),
        migrations.AddField(
            model_name='port',
            name='cabPlacement',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Расположение'),
        ),
        migrations.AddField(
            model_name='port',
            name='portType',
            field=models.CharField(choices=[('TRUNK', 'TRUNK'), ('ACCESS', 'ACCESS')], default='', max_length=50, verbose_name='Тип порта'),
        ),
        migrations.AddField(
            model_name='port',
            name='vlanNum',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='VLAN'),
        ),
        migrations.AddField(
            model_name='switch',
            name='inventoryNum',
            field=models.CharField(default='', max_length=50, verbose_name='Инвентарный номер'),
        ),
        migrations.AddField(
            model_name='switch',
            name='macAddr',
            field=models.CharField(default='', max_length=50, verbose_name='MAC-Адрес'),
        ),
        migrations.AddField(
            model_name='switch',
            name='placement',
            field=models.CharField(default='', max_length=100, verbose_name='Расположение'),
        ),
        migrations.AddField(
            model_name='switch',
            name='serialNum',
            field=models.CharField(default='', max_length=50, verbose_name='Серийный номер'),
        ),
    ]
