# Generated by Django 5.2.5 on 2025-08-15 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switchinfo', '0002_port_addinfo_port_cabplacement_port_porttype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='port',
            name='upLink',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Up Link'),
        ),
    ]
